In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("/housing.csv")
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562390,5.322283,6.299250,3.140000,29403.928700,9.975771e+05
50%,68804.286405,5.970429,7.002902,4.050000,36199.406690,1.232669e+06
75%,75783.338665,6.650808,7.665871,4.490000,42861.290770,1.471210e+06
max,107701.748400,9.519088,10.759588,6.500000,69621.713380,2.469066e+06

In [8]:
df.nunique()

Avg. Area Income                5000
Avg. Area House Age             5000
Avg. Area Number of Rooms       5000
Avg. Area Number of Bedrooms     255
Area Population                 5000
Price                           5000
Address                         5000
dtype: int64

In [ ]:
df['ocean_proximity'].value_counts()

In [ ]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)

In [11]:
df.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [12]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [13]:
print(df)

      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188
1          79248.64245             6.002900                   6.730821
2          61287.06718             5.865890                   8.512727
3          63345.24005             7.188236                   5.586729
4          59982.19723             5.040555                   7.839388
...                ...                  ...                        ...
4995       60567.94414             7.830362                   6.137356
4996       78491.27543             6.999135                   6.576763
4997       63390.68689             7.250591                   4.805081
4998       68001.33124             5.534388                   7.130144
4999       65510.58180             5.992305                   6.792336

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09      23086.80050  1.059034e+06
1                             3.09      40173.07217  1.505891e+06
2                             5.13      36882.15940  1.058988e+06
3                             3.26      34310.24283  1.260617e+06
4                             4.23      26354.10947  6.309435e+05
...                            ...              ...           ...
4995                          3.46      22837.36103  1.060194e+06
4996                          4.02      25616.11549  1.482618e+06
4997                          2.13      33266.14549  1.030730e+06
4998                          5.44      42625.62016  1.198657e+06
4999                          4.07      46501.28380  1.298950e+06

                                                Address
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1     188 Johnson Views Suite 079\nLake Kathleen, CA...
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3                             USS Barnett\nFPO AP 44820
4                            USNS Raymond\nFPO AE 09386
...                                                 ...
4995                   USNS Williams\nFPO AP 30153-7653
4996              PSC 9258, Box 8489\nAPO AA 42991-3352
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...
4998                          USS Wallace\nFPO AE 73316
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...

[5000 rows x 7 columns]

In [14]:
from sklearn.model_selection import train_test_split

X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

KeyError: "['median_house_value'] not found in axis"

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
import numpy as np
data = np.array(df)
normalizedData = (data-np.min(data))/(np.max(data)-np.min(data))
# normalized data using min max value
#file2 = normalizedData
print(normalizedData)

[[4.23893730e-06 3.24378678e-04 3.30617114e-04 ... 5.00574506e-04
  2.65283893e-04 9.05221761e-01]
 [4.25893229e-06 3.24338688e-04 2.90627140e-04 ... 2.52406722e-03
  2.65236305e-04 7.17068931e-01]
 [4.21894231e-06 3.24318693e-04 3.52611600e-04 ... 6.02548941e-04
  2.63148829e-04 7.04272139e-01]
 ...
 [6.25843101e-06 3.27477901e-04 2.82629145e-04 ... 1.11442061e-03
  2.52036814e-04 1.84802370e-01]
 [6.05848114e-06 3.27477901e-04 2.84628644e-04 ... 9.46462722e-04
  2.52371131e-04 1.69606180e-01]
 [6.21844104e-06 3.27357931e-04 2.80629646e-04 ... 1.30837199e-03
  2.53413669e-04 1.79003824e-01]]